[package]
name = "morgan-config-program"
version = "0.15.3"
description = "config program"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
morgan-config-api = { path = "../config_api", version = "0.15.3"     }
morgan-logger = { path = "../../logger", version = "0.15.3"     }
morgan-sdk = { path = "../../sdk", version = "0.15.3"     }

[lib]
name = "morgan_config_program"
crate-type = ["lib","cdylib"]
