[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-replicator"
version = "0.15.3"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
solana = { path = "../core", version = "0.15.3"     }
solana-logger = { path = "../logger", version = "0.15.3"     }
solana-netutil = { path = "../netutil", version = "0.15.3"     }
solana-sdk = { path = "../sdk", version = "0.15.3"     }

[features]
chacha = ["solana/chacha"]
cuda = ["solana/cuda"]
